project: 
  type: website
  output-dir: docs
  
website:
  title: "Staturn Courses"
  navbar:
    left:
      - href: courses.qmd
        text: Courses
      - href: resources.qmd
        text: Resources
  page-footer:
      center: "© 2026 Tyler Wiederich"
      right:
        - icon: github
          href: https://github.com/staturn-courses/staturn-courses.github.io
format: 
  html:
    theme: flatly
    toc: true
    
    
execute:
  eval: false
  